import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import RootLayout, { metadata } from "../layout";

vi.mock("next/font/google", () => ({
  Roboto: () => ({
    variable: "roboto",
  }),
  Geist_Mono: () => ({
    variable: "geist-mono",
  }),
}));

describe("RootLayout", () => {
  it("deve renderizar os children", () => {
    render(
      <RootLayout>
        <div>Olá Mundo</div>
      </RootLayout>
    );

    expect(screen.getByText("Olá Mundo")).toBeInTheDocument();
  });

  it("deve renderizar o html com lang='en'", () => {
    render(
      <RootLayout>
        <div>Teste</div>
      </RootLayout>
    );

    expect(document.documentElement.lang).toBe("en");
  });

  it("deve exportar os metadados corretamente", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});
